# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QFrame,
    QGroupBox, QHeaderView, QKeySequenceEdit, QLabel,
    QLayout, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStackedWidget, QTableWidget, QTableWidgetItem,
    QToolBox, QWidget)

class Ui_Admin_Page(object):
    def setupUi(self, Admin_Page):
        if not Admin_Page.objectName():
            Admin_Page.setObjectName(u"Admin_Page")
        Admin_Page.resize(1280, 720)
        Admin_Page.setMinimumSize(QSize(1280, 720))
        Admin_Page.setMaximumSize(QSize(1280, 720))
        self.PAGE = QWidget(Admin_Page)
        self.PAGE.setObjectName(u"PAGE")
        self.side_bar = QGroupBox(self.PAGE)
        self.side_bar.setObjectName(u"side_bar")
        self.side_bar.setGeometry(QRect(0, -10, 290, 731))
        self.side_bar.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.Dashboard_button = QPushButton(self.side_bar)
        self.Dashboard_button.setObjectName(u"Dashboard_button")
        self.Dashboard_button.setGeometry(QRect(-10, 140, 301, 81))
        font = QFont()
        font.setFamilies([u"Book Antiqua"])
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.Dashboard_button.setFont(font)
        self.Dashboard_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.Dashboard_button.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 15pt \"Book Antiqua\";")
        icon = QIcon()
        icon.addFile(u"Images/Dashboard.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Dashboard_button.setIcon(icon)
        self.Dashboard_button.setIconSize(QSize(25, 25))
        self.attendance = QPushButton(self.side_bar)
        self.attendance.setObjectName(u"attendance")
        self.attendance.setGeometry(QRect(0, 220, 291, 81))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.attendance.setFont(font1)
        self.attendance.setCursor(QCursor(Qt.PointingHandCursor))
        self.attendance.setStyleSheet(u"color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u"Images/attendance.png", QSize(), QIcon.Normal, QIcon.Off)
        self.attendance.setIcon(icon1)
        self.attendance.setIconSize(QSize(25, 25))
        self.attendance.setAutoDefault(False)
        self.attendance.setFlat(False)
        self.EandL = QToolBox(self.side_bar)
        self.EandL.setObjectName(u"EandL")
        self.EandL.setEnabled(True)
        self.EandL.setGeometry(QRect(0, 300, 291, 350))
        self.EandL.setMinimumSize(QSize(250, 300))
        self.EandL.setMaximumSize(QSize(300, 350))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        self.EandL.setFont(font2)
        self.EandL.setCursor(QCursor(Qt.PointingHandCursor))
        self.EandL.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.EandL.setFrameShape(QFrame.NoFrame)
        self.EandL.setFrameShadow(QFrame.Plain)
        self.EandL.setLineWidth(0)
        self.Employee = QWidget()
        self.Employee.setObjectName(u"Employee")
        self.Employee.setGeometry(QRect(0, 0, 291, 256))
        self.list_employee = QPushButton(self.Employee)
        self.list_employee.setObjectName(u"list_employee")
        self.list_employee.setGeometry(QRect(0, 0, 291, 71))
        font3 = QFont()
        font3.setPointSize(15)
        self.list_employee.setFont(font3)
        self.list_employee.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u"Images/list.png", QSize(), QIcon.Normal, QIcon.Off)
        self.list_employee.setIcon(icon2)
        self.list_employee.setIconSize(QSize(30, 30))
        self.Add_employee = QPushButton(self.Employee)
        self.Add_employee.setObjectName(u"Add_employee")
        self.Add_employee.setGeometry(QRect(0, 70, 291, 81))
        self.Add_employee.setFont(font3)
        self.Add_employee.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u"Images/add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Add_employee.setIcon(icon3)
        self.Add_employee.setIconSize(QSize(30, 30))
        self.Remove_employee = QPushButton(self.Employee)
        self.Remove_employee.setObjectName(u"Remove_employee")
        self.Remove_employee.setGeometry(QRect(0, 150, 291, 71))
        self.Remove_employee.setFont(font3)
        self.Remove_employee.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u"Images/remove.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Remove_employee.setIcon(icon4)
        self.Remove_employee.setIconSize(QSize(30, 30))
        icon5 = QIcon()
        icon5.addFile(u"Images/Employee.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.EandL.addItem(self.Employee, icon5, u"Employee")
        self.Leave = QWidget()
        self.Leave.setObjectName(u"Leave")
        self.Leave.setGeometry(QRect(0, 0, 291, 256))
        self.Pending = QPushButton(self.Leave)
        self.Pending.setObjectName(u"Pending")
        self.Pending.setGeometry(QRect(0, 0, 291, 81))
        self.Pending.setFont(font3)
        self.Pending.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u"Images/pending.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Pending.setIcon(icon6)
        self.Pending.setIconSize(QSize(30, 30))
        self.Approve = QPushButton(self.Leave)
        self.Approve.setObjectName(u"Approve")
        self.Approve.setGeometry(QRect(0, 80, 291, 81))
        self.Approve.setFont(font3)
        self.Approve.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u"Images/approve.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Approve.setIcon(icon7)
        self.Approve.setIconSize(QSize(30, 30))
        self.Decline = QPushButton(self.Leave)
        self.Decline.setObjectName(u"Decline")
        self.Decline.setGeometry(QRect(0, 160, 291, 81))
        self.Decline.setFont(font3)
        self.Decline.setCursor(QCursor(Qt.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u"Images/decline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Decline.setIcon(icon8)
        self.Decline.setIconSize(QSize(30, 30))
        icon9 = QIcon()
        icon9.addFile(u"Images/leave.png", QSize(), QIcon.Normal, QIcon.Off)
        self.EandL.addItem(self.Leave, icon9, u"Leave")
        self.Logo = QLabel(self.side_bar)
        self.Logo.setObjectName(u"Logo")
        self.Logo.setGeometry(QRect(0, 10, 290, 131))
        self.Logo.setPixmap(QPixmap(u"Images/logo.png"))
        self.Logo.setScaledContents(True)
        self.Main_pages = QStackedWidget(self.PAGE)
        self.Main_pages.setObjectName(u"Main_pages")
        self.Main_pages.setEnabled(True)
        self.Main_pages.setGeometry(QRect(290, 10, 990, 720))
        self.Main_pages.setMinimumSize(QSize(990, 720))
        self.dashboard_page = QWidget()
        self.dashboard_page.setObjectName(u"dashboard_page")
        self.dashboard_page.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.title_bar = QGroupBox(self.dashboard_page)
        self.title_bar.setObjectName(u"title_bar")
        self.title_bar.setGeometry(QRect(0, 60, 991, 80))
        self.Dashboard_text = QLabel(self.title_bar)
        self.Dashboard_text.setObjectName(u"Dashboard_text")
        self.Dashboard_text.setGeometry(QRect(30, 20, 181, 31))
        font4 = QFont()
        font4.setPointSize(20)
        self.Dashboard_text.setFont(font4)
        self.home_text = QLabel(self.title_bar)
        self.home_text.setObjectName(u"home_text")
        self.home_text.setGeometry(QRect(220, 27, 91, 21))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(True)
        self.home_text.setFont(font5)
        self.home_text.setStyleSheet(u"color: rgb(88, 55, 89);")
        self.HR_dashboard_text = QLabel(self.title_bar)
        self.HR_dashboard_text.setObjectName(u"HR_dashboard_text")
        self.HR_dashboard_text.setGeometry(QRect(320, 27, 171, 21))
        font6 = QFont()
        font6.setPointSize(13)
        self.HR_dashboard_text.setFont(font6)
        self.active_employee = QGroupBox(self.dashboard_page)
        self.active_employee.setObjectName(u"active_employee")
        self.active_employee.setGeometry(QRect(80, 190, 350, 200))
        self.active_employee.setStyleSheet(u"background-color:rgb(169,169,169);\n"
"\n"
"border-radius:30px;\n"
"")
        self.active_employee_text = QLabel(self.active_employee)
        self.active_employee_text.setObjectName(u"active_employee_text")
        self.active_employee_text.setGeometry(QRect(70, 20, 271, 41))
        font7 = QFont()
        font7.setPointSize(25)
        font7.setBold(False)
        self.active_employee_text.setFont(font7)
        self.active_employee_text.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);")
        self.active_employee_count = QLabel(self.active_employee)
        self.active_employee_count.setObjectName(u"active_employee_count")
        self.active_employee_count.setGeometry(QRect(140, 80, 81, 91))
        font8 = QFont()
        font8.setPointSize(50)
        self.active_employee_count.setFont(font8)
        self.active_employee_count.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);")
        self.active_employee_logo = QLabel(self.active_employee)
        self.active_employee_logo.setObjectName(u"active_employee_logo")
        self.active_employee_logo.setGeometry(QRect(10, 20, 51, 41))
        self.active_employee_logo.setPixmap(QPixmap(u"Images/toppng.com-free-twitter-white-icon-employee-icon-white-537x501.png"))
        self.active_employee_logo.setScaledContents(True)
        self.pending_leaves = QGroupBox(self.dashboard_page)
        self.pending_leaves.setObjectName(u"pending_leaves")
        self.pending_leaves.setGeometry(QRect(540, 190, 350, 200))
        self.pending_leaves.setStyleSheet(u"\n"
"background-color: rgb(116, 118, 128);\n"
"border-radius:30px;")
        self.pending_leaves_text = QLabel(self.pending_leaves)
        self.pending_leaves_text.setObjectName(u"pending_leaves_text")
        self.pending_leaves_text.setGeometry(QRect(90, 20, 241, 41))
        font9 = QFont()
        font9.setPointSize(25)
        self.pending_leaves_text.setFont(font9)
        self.pending_leaves_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pending_leaves_logo = QLabel(self.pending_leaves)
        self.pending_leaves_logo.setObjectName(u"pending_leaves_logo")
        self.pending_leaves_logo.setGeometry(QRect(20, 20, 47, 41))
        self.pending_leaves_logo.setPixmap(QPixmap(u"Images/pending_logo.png"))
        self.pending_leaves_logo.setScaledContents(True)
        self.pending_leaves_count = QLabel(self.pending_leaves)
        self.pending_leaves_count.setObjectName(u"pending_leaves_count")
        self.pending_leaves_count.setGeometry(QRect(150, 100, 101, 61))
        self.pending_leaves_count.setFont(font8)
        self.pending_leaves_count.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.approved_leaves = QGroupBox(self.dashboard_page)
        self.approved_leaves.setObjectName(u"approved_leaves")
        self.approved_leaves.setGeometry(QRect(80, 460, 350, 200))
        self.approved_leaves.setStyleSheet(u"background-color: rgb(140, 146, 172);\n"
"border-radius:30px;")
        self.approved_leaves_logo = QLabel(self.approved_leaves)
        self.approved_leaves_logo.setObjectName(u"approved_leaves_logo")
        self.approved_leaves_logo.setGeometry(QRect(10, 20, 47, 41))
        self.approved_leaves_logo.setPixmap(QPixmap(u"Images/approve_logo.png"))
        self.approved_leaves_logo.setScaledContents(True)
        self.approved_leaves_text = QLabel(self.approved_leaves)
        self.approved_leaves_text.setObjectName(u"approved_leaves_text")
        self.approved_leaves_text.setGeometry(QRect(70, 20, 261, 41))
        self.approved_leaves_text.setFont(font9)
        self.approved_leaves_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.approved_leaves_count = QLabel(self.approved_leaves)
        self.approved_leaves_count.setObjectName(u"approved_leaves_count")
        self.approved_leaves_count.setGeometry(QRect(150, 80, 61, 81))
        self.approved_leaves_count.setFont(font8)
        self.approved_leaves_count.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.declined_leaves = QGroupBox(self.dashboard_page)
        self.declined_leaves.setObjectName(u"declined_leaves")
        self.declined_leaves.setGeometry(QRect(540, 460, 350, 200))
        self.declined_leaves.setStyleSheet(u"background-color: rgb(98, 112, 156);\n"
"border-radius:30px;")
        self.declined_leaves_logo = QLabel(self.declined_leaves)
        self.declined_leaves_logo.setObjectName(u"declined_leaves_logo")
        self.declined_leaves_logo.setGeometry(QRect(10, 10, 61, 51))
        self.declined_leaves_logo.setPixmap(QPixmap(u"Images/Decline_logo.png"))
        self.declined_leaves_logo.setScaledContents(True)
        self.declined_leaves_text = QLabel(self.declined_leaves)
        self.declined_leaves_text.setObjectName(u"declined_leaves_text")
        self.declined_leaves_text.setGeometry(QRect(70, 10, 251, 51))
        self.declined_leaves_text.setFont(font9)
        self.declined_leaves_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.declined_leaves_count = QLabel(self.declined_leaves)
        self.declined_leaves_count.setObjectName(u"declined_leaves_count")
        self.declined_leaves_count.setGeometry(QRect(140, 90, 91, 61))
        self.declined_leaves_count.setFont(font8)
        self.declined_leaves_count.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Main_pages.addWidget(self.dashboard_page)
        self.Employeelist_page = QWidget()
        self.Employeelist_page.setObjectName(u"Employeelist_page")
        self.List_title_bar = QGroupBox(self.Employeelist_page)
        self.List_title_bar.setObjectName(u"List_title_bar")
        self.List_title_bar.setGeometry(QRect(0, 40, 991, 80))
        self.List_title_bar.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.List_employee_text = QLabel(self.List_title_bar)
        self.List_employee_text.setObjectName(u"List_employee_text")
        self.List_employee_text.setGeometry(QRect(33, 22, 261, 31))
        font10 = QFont()
        font10.setPointSize(18)
        self.List_employee_text.setFont(font10)
        self.List_employee_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.List = QTableWidget(self.Employeelist_page)
        if (self.List.columnCount() < 4):
            self.List.setColumnCount(4)
        font11 = QFont()
        font11.setBold(True)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font11);
        self.List.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font11);
        self.List.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font11);
        self.List.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setFont(font11);
        self.List.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.List.setObjectName(u"List")
        self.List.setGeometry(QRect(25, 221, 925, 331))
        self.List.setStyleSheet(u"QHeaderView::section {\n"
"    background-color: rgb(88, 55, 89); /* Set your desired background color */\n"
"    color: white; /* Set the text color */\n"
"    border: 1px solid rgb(88, 55, 89); /* Set the border color */\n"
"}")
        self.List.setShowGrid(True)
        self.List.setSortingEnabled(False)
        self.List.setRowCount(0)
        self.List.horizontalHeader().setCascadingSectionResizes(False)
        self.List.horizontalHeader().setDefaultSectionSize(230)
        self.List.horizontalHeader().setHighlightSections(False)
        self.List.horizontalHeader().setProperty("showSortIndicator", False)
        self.List.horizontalHeader().setStretchLastSection(False)
        self.List.verticalHeader().setCascadingSectionResizes(False)
        self.List.verticalHeader().setMinimumSectionSize(25)
        self.List.verticalHeader().setProperty("showSortIndicator", False)
        self.List.verticalHeader().setStretchLastSection(False)
        self.Main_pages.addWidget(self.Employeelist_page)
        self.AddEmployee_Page = QWidget()
        self.AddEmployee_Page.setObjectName(u"AddEmployee_Page")
        self.New_employee_bar = QGroupBox(self.AddEmployee_Page)
        self.New_employee_bar.setObjectName(u"New_employee_bar")
        self.New_employee_bar.setGeometry(QRect(0, 20, 991, 80))
        self.New_employee_bar.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.new_employee_text = QLabel(self.New_employee_bar)
        self.new_employee_text.setObjectName(u"new_employee_text")
        self.new_employee_text.setGeometry(QRect(33, 22, 261, 31))
        self.new_employee_text.setFont(font10)
        self.new_employee_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Department = QComboBox(self.AddEmployee_Page)
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.setObjectName(u"Department")
        self.Department.setGeometry(QRect(210, 160, 210, 30))
        self.Department.setFont(font6)
        self.Department.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;")
        self.Employee_id = QLineEdit(self.AddEmployee_Page)
        self.Employee_id.setObjectName(u"Employee_id")
        self.Employee_id.setGeometry(QRect(660, 160, 210, 30))
        self.Employee_id.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Contact = QLineEdit(self.AddEmployee_Page)
        self.Contact.setObjectName(u"Contact")
        self.Contact.setGeometry(QRect(210, 380, 211, 31))
        self.Contact.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Lname = QLineEdit(self.AddEmployee_Page)
        self.Lname.setObjectName(u"Lname")
        self.Lname.setGeometry(QRect(660, 270, 211, 31))
        self.Lname.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Fname = QLineEdit(self.AddEmployee_Page)
        self.Fname.setObjectName(u"Fname")
        self.Fname.setGeometry(QRect(210, 270, 211, 31))
        self.Fname.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Address = QLineEdit(self.AddEmployee_Page)
        self.Address.setObjectName(u"Address")
        self.Address.setGeometry(QRect(660, 380, 211, 31))
        self.Address.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Email = QLineEdit(self.AddEmployee_Page)
        self.Email.setObjectName(u"Email")
        self.Email.setGeometry(QRect(210, 490, 211, 31))
        self.Email.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.password = QLineEdit(self.AddEmployee_Page)
        self.password.setObjectName(u"password")
        self.password.setGeometry(QRect(660, 490, 211, 31))
        self.password.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.password.setEchoMode(QLineEdit.Password)
        self.Department_Text = QLabel(self.AddEmployee_Page)
        self.Department_Text.setObjectName(u"Department_Text")
        self.Department_Text.setGeometry(QRect(90, 165, 111, 21))
        font12 = QFont()
        font12.setPointSize(13)
        font12.setBold(True)
        self.Department_Text.setFont(font12)
        self.Employee_id_text = QLabel(self.AddEmployee_Page)
        self.Employee_id_text.setObjectName(u"Employee_id_text")
        self.Employee_id_text.setGeometry(QRect(530, 165, 121, 21))
        self.Employee_id_text.setFont(font12)
        self.Fname_text = QLabel(self.AddEmployee_Page)
        self.Fname_text.setObjectName(u"Fname_text")
        self.Fname_text.setGeometry(QRect(90, 275, 101, 21))
        self.Fname_text.setFont(font12)
        self.Lname_text = QLabel(self.AddEmployee_Page)
        self.Lname_text.setObjectName(u"Lname_text")
        self.Lname_text.setGeometry(QRect(530, 275, 101, 21))
        self.Lname_text.setFont(font12)
        self.Contact_text = QLabel(self.AddEmployee_Page)
        self.Contact_text.setObjectName(u"Contact_text")
        self.Contact_text.setGeometry(QRect(90, 385, 101, 21))
        self.Contact_text.setFont(font12)
        self.Address_text = QLabel(self.AddEmployee_Page)
        self.Address_text.setObjectName(u"Address_text")
        self.Address_text.setGeometry(QRect(530, 385, 101, 21))
        self.Address_text.setFont(font12)
        self.Email_text = QLabel(self.AddEmployee_Page)
        self.Email_text.setObjectName(u"Email_text")
        self.Email_text.setGeometry(QRect(90, 495, 101, 21))
        self.Email_text.setFont(font12)
        self.Password_text = QLabel(self.AddEmployee_Page)
        self.Password_text.setObjectName(u"Password_text")
        self.Password_text.setGeometry(QRect(530, 495, 101, 21))
        self.Password_text.setFont(font12)
        self.add_button = QPushButton(self.AddEmployee_Page)
        self.add_button.setObjectName(u"add_button")
        self.add_button.setGeometry(QRect(420, 650, 111, 31))
        font13 = QFont()
        font13.setPointSize(10)
        font13.setBold(True)
        self.add_button.setFont(font13)
        self.add_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.add_button.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(88, 55, 89);\n"
"color: rgb(255, 255, 255);")
        self.Salary_text = QLabel(self.AddEmployee_Page)
        self.Salary_text.setObjectName(u"Salary_text")
        self.Salary_text.setGeometry(QRect(310, 580, 101, 21))
        self.Salary_text.setFont(font12)
        self.Salary = QLineEdit(self.AddEmployee_Page)
        self.Salary.setObjectName(u"Salary")
        self.Salary.setGeometry(QRect(390, 575, 211, 31))
        self.Salary.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Main_pages.addWidget(self.AddEmployee_Page)
        self.Removeemployee_page = QWidget()
        self.Removeemployee_page.setObjectName(u"Removeemployee_page")
        self.Remove_bar = QGroupBox(self.Removeemployee_page)
        self.Remove_bar.setObjectName(u"Remove_bar")
        self.Remove_bar.setGeometry(QRect(0, 0, 991, 80))
        self.Remove_bar.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.Remove_text = QLabel(self.Remove_bar)
        self.Remove_text.setObjectName(u"Remove_text")
        self.Remove_text.setGeometry(QRect(60, 20, 261, 31))
        self.Remove_text.setFont(font10)
        self.Remove_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Enter_ID = QLabel(self.Removeemployee_page)
        self.Enter_ID.setObjectName(u"Enter_ID")
        self.Enter_ID.setGeometry(QRect(320, 260, 311, 51))
        self.Enter_ID.setFont(font4)
        self.Enter_ID.setStyleSheet(u"background-color: rgb(88, 55, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.Enter_ID.setAlignment(Qt.AlignCenter)
        self.ID_box = QLineEdit(self.Removeemployee_page)
        self.ID_box.setObjectName(u"ID_box")
        self.ID_box.setGeometry(QRect(370, 370, 201, 31))
        self.ID_box.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Remove = QPushButton(self.Removeemployee_page)
        self.Remove.setObjectName(u"Remove")
        self.Remove.setGeometry(QRect(425, 440, 90, 30))
        self.Remove.setFont(font11)
        self.Remove.setCursor(QCursor(Qt.PointingHandCursor))
        self.Remove.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(175, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Main_pages.addWidget(self.Removeemployee_page)
        self.Employee_Detail_Page = QWidget()
        self.Employee_Detail_Page.setObjectName(u"Employee_Detail_Page")
        self.Email_2 = QLineEdit(self.Employee_Detail_Page)
        self.Email_2.setObjectName(u"Email_2")
        self.Email_2.setGeometry(QRect(210, 455, 211, 31))
        self.Email_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Address_2 = QLineEdit(self.Employee_Detail_Page)
        self.Address_2.setObjectName(u"Address_2")
        self.Address_2.setGeometry(QRect(660, 345, 211, 31))
        self.Address_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Salary_2 = QLineEdit(self.Employee_Detail_Page)
        self.Salary_2.setObjectName(u"Salary_2")
        self.Salary_2.setGeometry(QRect(390, 540, 211, 31))
        self.Salary_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Contact_2 = QLineEdit(self.Employee_Detail_Page)
        self.Contact_2.setObjectName(u"Contact_2")
        self.Contact_2.setGeometry(QRect(210, 345, 211, 31))
        self.Contact_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Department_Text_2 = QLabel(self.Employee_Detail_Page)
        self.Department_Text_2.setObjectName(u"Department_Text_2")
        self.Department_Text_2.setGeometry(QRect(90, 130, 111, 21))
        self.Department_Text_2.setFont(font12)
        self.Lname_2 = QLineEdit(self.Employee_Detail_Page)
        self.Lname_2.setObjectName(u"Lname_2")
        self.Lname_2.setGeometry(QRect(660, 235, 211, 31))
        self.Lname_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Fname_2 = QLineEdit(self.Employee_Detail_Page)
        self.Fname_2.setObjectName(u"Fname_2")
        self.Fname_2.setGeometry(QRect(210, 235, 211, 31))
        self.Fname_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.View_Edit = QGroupBox(self.Employee_Detail_Page)
        self.View_Edit.setObjectName(u"View_Edit")
        self.View_Edit.setGeometry(QRect(0, -15, 991, 80))
        self.View_Edit.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.View_edit_text = QLabel(self.View_Edit)
        self.View_edit_text.setObjectName(u"View_edit_text")
        self.View_edit_text.setGeometry(QRect(33, 30, 261, 31))
        self.View_edit_text.setFont(font10)
        self.View_edit_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.password_2 = QLineEdit(self.Employee_Detail_Page)
        self.password_2.setObjectName(u"password_2")
        self.password_2.setGeometry(QRect(660, 455, 211, 31))
        self.password_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.password_2.setEchoMode(QLineEdit.Password)
        self.Employee_id_2 = QLineEdit(self.Employee_Detail_Page)
        self.Employee_id_2.setObjectName(u"Employee_id_2")
        self.Employee_id_2.setGeometry(QRect(660, 125, 210, 30))
        self.Employee_id_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.Password_text_2 = QLabel(self.Employee_Detail_Page)
        self.Password_text_2.setObjectName(u"Password_text_2")
        self.Password_text_2.setGeometry(QRect(530, 460, 101, 21))
        self.Password_text_2.setFont(font12)
        self.Contact_text_2 = QLabel(self.Employee_Detail_Page)
        self.Contact_text_2.setObjectName(u"Contact_text_2")
        self.Contact_text_2.setGeometry(QRect(90, 350, 101, 21))
        self.Contact_text_2.setFont(font12)
        self.Employee_id_text_2 = QLabel(self.Employee_Detail_Page)
        self.Employee_id_text_2.setObjectName(u"Employee_id_text_2")
        self.Employee_id_text_2.setGeometry(QRect(530, 130, 121, 21))
        self.Employee_id_text_2.setFont(font12)
        self.Email_text_2 = QLabel(self.Employee_Detail_Page)
        self.Email_text_2.setObjectName(u"Email_text_2")
        self.Email_text_2.setGeometry(QRect(90, 460, 101, 21))
        self.Email_text_2.setFont(font12)
        self.Save_button = QPushButton(self.Employee_Detail_Page)
        self.Save_button.setObjectName(u"Save_button")
        self.Save_button.setGeometry(QRect(420, 615, 111, 31))
        self.Save_button.setFont(font13)
        self.Save_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.Save_button.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(88, 55, 89);\n"
"color: rgb(255, 255, 255);")
        self.Lname_text_2 = QLabel(self.Employee_Detail_Page)
        self.Lname_text_2.setObjectName(u"Lname_text_2")
        self.Lname_text_2.setGeometry(QRect(530, 240, 101, 21))
        self.Lname_text_2.setFont(font12)
        self.Fname_text_2 = QLabel(self.Employee_Detail_Page)
        self.Fname_text_2.setObjectName(u"Fname_text_2")
        self.Fname_text_2.setGeometry(QRect(90, 240, 101, 21))
        self.Fname_text_2.setFont(font12)
        self.Salary_text_2 = QLabel(self.Employee_Detail_Page)
        self.Salary_text_2.setObjectName(u"Salary_text_2")
        self.Salary_text_2.setGeometry(QRect(310, 545, 101, 21))
        self.Salary_text_2.setFont(font12)
        self.Address_text_2 = QLabel(self.Employee_Detail_Page)
        self.Address_text_2.setObjectName(u"Address_text_2")
        self.Address_text_2.setGeometry(QRect(530, 350, 101, 21))
        self.Address_text_2.setFont(font12)
        self.Department_2 = QLineEdit(self.Employee_Detail_Page)
        self.Department_2.setObjectName(u"Department_2")
        self.Department_2.setGeometry(QRect(210, 125, 210, 30))
        self.Department_2.setStyleSheet(u"border:1px solid;\n"
"border-radius:15px;\n"
"")
        self.back_button = QPushButton(self.Employee_Detail_Page)
        self.back_button.setObjectName(u"back_button")
        self.back_button.setGeometry(QRect(40, 80, 111, 31))
        self.back_button.setFont(font13)
        self.back_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.back_button.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(88, 55, 89);\n"
"color: rgb(255, 255, 255);")
        self.Main_pages.addWidget(self.Employee_Detail_Page)
        self.Attendance = QWidget()
        self.Attendance.setObjectName(u"Attendance")
        self.Date = QDateEdit(self.Attendance)
        self.Date.setObjectName(u"Date")
        self.Date.setGeometry(QRect(230, 130, 110, 22))
        self.Date.setMaximumDate(QDate(2023, 12, 31))
        self.Date.setMinimumDate(QDate(2000, 1, 1))
        self.Date.setCalendarPopup(True)
        self.Attendance_Bar = QGroupBox(self.Attendance)
        self.Attendance_Bar.setObjectName(u"Attendance_Bar")
        self.Attendance_Bar.setGeometry(QRect(0, 0, 991, 80))
        self.Attendance_Bar.setStyleSheet(u"background-color: rgb(88, 55, 89);")
        self.Attendance_bar_text = QLabel(self.Attendance_Bar)
        self.Attendance_bar_text.setObjectName(u"Attendance_bar_text")
        self.Attendance_bar_text.setGeometry(QRect(33, 22, 261, 31))
        self.Attendance_bar_text.setFont(font10)
        self.Attendance_bar_text.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Select_date = QLabel(self.Attendance)
        self.Select_date.setObjectName(u"Select_date")
        self.Select_date.setGeometry(QRect(110, 130, 121, 21))
        font14 = QFont()
        font14.setPointSize(12)
        font14.setBold(True)
        self.Select_date.setFont(font14)
        self.Select_date.setStyleSheet(u"color: rgb(88, 55, 89);")
        self.Attendance_sheet = QTableWidget(self.Attendance)
        if (self.Attendance_sheet.columnCount() < 5):
            self.Attendance_sheet.setColumnCount(5)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setFont(font11);
        self.Attendance_sheet.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setFont(font11);
        self.Attendance_sheet.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setFont(font11);
        self.Attendance_sheet.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setFont(font11);
        self.Attendance_sheet.setHorizontalHeaderItem(3, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font11);
        self.Attendance_sheet.setHorizontalHeaderItem(4, __qtablewidgetitem8)
        self.Attendance_sheet.setObjectName(u"Attendance_sheet")
        self.Attendance_sheet.setGeometry(QRect(30, 240, 925, 331))
        self.Attendance_sheet.setStyleSheet(u"QHeaderView::section {\n"
"    background-color: rgb(88, 55, 89); /* Set your desired background color */\n"
"    color: white; /* Set the text color */\n"
"    border: 1px solid rgb(88, 55, 89); /* Set the border color */\n"
"}")
        self.Attendance_sheet.setShowGrid(True)
        self.Attendance_sheet.setSortingEnabled(False)
        self.Attendance_sheet.setRowCount(0)
        self.Attendance_sheet.horizontalHeader().setCascadingSectionResizes(False)
        self.Attendance_sheet.horizontalHeader().setDefaultSectionSize(184)
        self.Attendance_sheet.horizontalHeader().setHighlightSections(False)
        self.Attendance_sheet.horizontalHeader().setProperty("showSortIndicator", False)
        self.Attendance_sheet.horizontalHeader().setStretchLastSection(False)
        self.Attendance_sheet.verticalHeader().setCascadingSectionResizes(False)
        self.Attendance_sheet.verticalHeader().setMinimumSectionSize(25)
        self.Attendance_sheet.verticalHeader().setProperty("showSortIndicator", False)
        self.Attendance_sheet.verticalHeader().setStretchLastSection(False)
        self.keySequenceEdit = QKeySequenceEdit(self.Attendance)
        self.keySequenceEdit.setObjectName(u"keySequenceEdit")
        self.keySequenceEdit.setGeometry(QRect(220, 530, 113, 20))
        self.Mark_button = QPushButton(self.Attendance)
        self.Mark_button.setObjectName(u"Mark_button")
        self.Mark_button.setGeometry(QRect(410, 630, 111, 31))
        self.Mark_button.setFont(font13)
        self.Mark_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.Mark_button.setStyleSheet(u"border-radius:15px;\n"
"background-color: rgb(88, 55, 89);\n"
"color: rgb(255, 255, 255);")
        self.Main_pages.addWidget(self.Attendance)
        Admin_Page.setCentralWidget(self.PAGE)

        self.retranslateUi(Admin_Page)

        self.attendance.setDefault(False)
        self.EandL.setCurrentIndex(0)
        self.EandL.layout().setSpacing(10)
        self.Main_pages.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(Admin_Page)
    # setupUi

    def retranslateUi(self, Admin_Page):
        Admin_Page.setWindowTitle(QCoreApplication.translate("Admin_Page", u"MainWindow", None))
        self.side_bar.setTitle(QCoreApplication.translate("Admin_Page", u"GroupBox", None))
        self.Dashboard_button.setText(QCoreApplication.translate("Admin_Page", u"Dashboard", None))
        self.attendance.setText(QCoreApplication.translate("Admin_Page", u"Attendance", None))
        self.list_employee.setText(QCoreApplication.translate("Admin_Page", u"List of Employee", None))
        self.Add_employee.setText(QCoreApplication.translate("Admin_Page", u"Add Employee", None))
        self.Remove_employee.setText(QCoreApplication.translate("Admin_Page", u"Remove Employee", None))
        self.EandL.setItemText(self.EandL.indexOf(self.Employee), QCoreApplication.translate("Admin_Page", u"Employee", None))
        self.Pending.setText(QCoreApplication.translate("Admin_Page", u"Pending", None))
        self.Approve.setText(QCoreApplication.translate("Admin_Page", u"Approved", None))
        self.Decline.setText(QCoreApplication.translate("Admin_Page", u"Declined", None))
        self.EandL.setItemText(self.EandL.indexOf(self.Leave), QCoreApplication.translate("Admin_Page", u"Leave", None))
        self.Logo.setText("")
        self.title_bar.setTitle("")
        self.Dashboard_text.setText(QCoreApplication.translate("Admin_Page", u"Dashboard", None))
        self.home_text.setText(QCoreApplication.translate("Admin_Page", u"Home  /", None))
        self.HR_dashboard_text.setText(QCoreApplication.translate("Admin_Page", u"HR's  Dashboard", None))
        self.active_employee.setTitle("")
        self.active_employee_text.setText(QCoreApplication.translate("Admin_Page", u"Active Employees", None))
        self.active_employee_count.setText(QCoreApplication.translate("Admin_Page", u"10", None))
        self.active_employee_logo.setText("")
        self.pending_leaves.setTitle("")
        self.pending_leaves_text.setText(QCoreApplication.translate("Admin_Page", u"Pending Leaves", None))
        self.pending_leaves_logo.setText("")
        self.pending_leaves_count.setText(QCoreApplication.translate("Admin_Page", u"4", None))
        self.approved_leaves.setTitle("")
        self.approved_leaves_logo.setText("")
        self.approved_leaves_text.setText(QCoreApplication.translate("Admin_Page", u"Approved Leaves", None))
        self.approved_leaves_count.setText(QCoreApplication.translate("Admin_Page", u"5", None))
        self.declined_leaves.setTitle("")
        self.declined_leaves_logo.setText("")
        self.declined_leaves_text.setText(QCoreApplication.translate("Admin_Page", u"Declined Leaves", None))
        self.declined_leaves_count.setText(QCoreApplication.translate("Admin_Page", u"11", None))
        self.List_title_bar.setTitle("")
        self.List_employee_text.setText(QCoreApplication.translate("Admin_Page", u"List of Employess", None))
        ___qtablewidgetitem = self.List.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Admin_Page", u"Employee ID", None));
        ___qtablewidgetitem1 = self.List.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Admin_Page", u"First Name", None));
        ___qtablewidgetitem2 = self.List.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Admin_Page", u"Last Name", None));
        ___qtablewidgetitem3 = self.List.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Admin_Page", u"Email", None));
        self.New_employee_bar.setTitle("")
        self.new_employee_text.setText(QCoreApplication.translate("Admin_Page", u"Add New Employee", None))
        self.Department.setItemText(0, QCoreApplication.translate("Admin_Page", u"    Marketing", None))
        self.Department.setItemText(1, QCoreApplication.translate("Admin_Page", u"    Accounts", None))
        self.Department.setItemText(2, QCoreApplication.translate("Admin_Page", u"    Sales", None))
        self.Department.setItemText(3, QCoreApplication.translate("Admin_Page", u"    Finance", None))
        self.Department.setItemText(4, QCoreApplication.translate("Admin_Page", u"    Research", None))

        self.Department_Text.setText(QCoreApplication.translate("Admin_Page", u"Department:", None))
        self.Employee_id_text.setText(QCoreApplication.translate("Admin_Page", u"Employee ID:", None))
        self.Fname_text.setText(QCoreApplication.translate("Admin_Page", u"First Name:", None))
        self.Lname_text.setText(QCoreApplication.translate("Admin_Page", u"Last Name:", None))
        self.Contact_text.setText(QCoreApplication.translate("Admin_Page", u"Contact #:", None))
        self.Address_text.setText(QCoreApplication.translate("Admin_Page", u"Address:", None))
        self.Email_text.setText(QCoreApplication.translate("Admin_Page", u"Email:", None))
        self.Password_text.setText(QCoreApplication.translate("Admin_Page", u"Password:", None))
        self.add_button.setText(QCoreApplication.translate("Admin_Page", u"ADD", None))
        self.Salary_text.setText(QCoreApplication.translate("Admin_Page", u"Salary:", None))
        self.Remove_bar.setTitle("")
        self.Remove_text.setText(QCoreApplication.translate("Admin_Page", u"Remove Employee", None))
        self.Enter_ID.setText(QCoreApplication.translate("Admin_Page", u"Enter Employee ID", None))
        self.Remove.setText(QCoreApplication.translate("Admin_Page", u"Remove", None))
        self.Department_Text_2.setText(QCoreApplication.translate("Admin_Page", u"Department:", None))
        self.View_Edit.setTitle("")
        self.View_edit_text.setText(QCoreApplication.translate("Admin_Page", u"View and Edit Employee", None))
        self.Password_text_2.setText(QCoreApplication.translate("Admin_Page", u"Password:", None))
        self.Contact_text_2.setText(QCoreApplication.translate("Admin_Page", u"Contact #:", None))
        self.Employee_id_text_2.setText(QCoreApplication.translate("Admin_Page", u"Employee ID:", None))
        self.Email_text_2.setText(QCoreApplication.translate("Admin_Page", u"Email:", None))
        self.Save_button.setText(QCoreApplication.translate("Admin_Page", u"Save", None))
        self.Lname_text_2.setText(QCoreApplication.translate("Admin_Page", u"Last Name:", None))
        self.Fname_text_2.setText(QCoreApplication.translate("Admin_Page", u"First Name:", None))
        self.Salary_text_2.setText(QCoreApplication.translate("Admin_Page", u"Salary:", None))
        self.Address_text_2.setText(QCoreApplication.translate("Admin_Page", u"Address:", None))
        self.back_button.setText(QCoreApplication.translate("Admin_Page", u"Back", None))
        self.Attendance_Bar.setTitle("")
        self.Attendance_bar_text.setText(QCoreApplication.translate("Admin_Page", u"Mark Attendance", None))
        self.Select_date.setText(QCoreApplication.translate("Admin_Page", u"Select Date:", None))
        ___qtablewidgetitem4 = self.Attendance_sheet.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Admin_Page", u"Employee ID", None));
        ___qtablewidgetitem5 = self.Attendance_sheet.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Admin_Page", u"First Name", None));
        ___qtablewidgetitem6 = self.Attendance_sheet.horizontalHeaderItem(2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Admin_Page", u"Last Name", None));
        ___qtablewidgetitem7 = self.Attendance_sheet.horizontalHeaderItem(3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Admin_Page", u"Date", None));
        ___qtablewidgetitem8 = self.Attendance_sheet.horizontalHeaderItem(4)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Admin_Page", u"Status", None));
        self.Mark_button.setText(QCoreApplication.translate("Admin_Page", u"Mark", None))
    # retranslateUi

